files:
  "src/item.c":             {".text": [0x08a18c40, 0x08a18dc0]}
  "src/item_data.c":        {".text": [0x08a18600, 0x08a18680]}
  "src/data_item_table.c":  {".data": [0x08b29288, 0x08b2a2a8]}
  "src/data_item_table2.c": {".data": [0x08a5adac, 0x08a5b07c]}
